
name: Build and Deploy Landing Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        landing-page: [
          'fenix/fenix-5-rodadas',
          'fenix/fenix-10-rodadas',
          'touro/touro-1-real',
          'touro/touro-5-reais',
          'touro/touro-10-reais',
          'cachorro/cachorro-1-real',
          'cachorro/cachorro-5-reais',
          'aviator/aviator-1-real',
          'aviator/aviator-5-reais',
          'aviator/aviator-10-reais'
        ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: '${{ matrix.landing-page }}/package-lock.json'
    
    - name: Install dependencies
      run: |
        cd ${{ matrix.landing-page }}
        npm ci
    
    - name: Run tests
      run: |
        cd ${{ matrix.landing-page }}
        npm run test --if-present
    
    - name: Build
      run: |
        cd ${{ matrix.landing-page }}
        npm run build
    
    - name: Run Lighthouse CI
      uses: treosh/lighthouse-ci-action@v10
      with:
        configPath: './.lighthouserc.json'
        uploadDir: '${{ matrix.landing-page }}/dist'
    
    - name: Deploy to Netlify
      if: github.ref == 'refs/heads/main'
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: '${{ matrix.landing-page }}/dist'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions - ${{ matrix.landing-page }}"
        enable-pull-request-comment: true
        enable-commit-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  lighthouse-report:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Comment PR with Lighthouse scores
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🚨 Lighthouse scores updated! Check the Actions tab for detailed reports.'
          })
